import "./modules/loader";
import "./gsap/smooth-scroll";
import "@pug/blocks/hero-section/hero-section";
import "@pug/blocks/services-preview/services-preview";
import "@pug/blocks/horses-preview/horses-preview";
import "@pug/blocks/coach-preview/coach-preview";
// import "@pug/blocks/gallery-preview/gallery-preview";
// import "@pug/blocks/gallery-preview/gallery-preview-slider";
import "@pug/blocks/features/features";
import "@pug/components/static/transition-block/transition-block";
// import "./gsap/test";
